
credentials:

  system:
    domainCredentials:
      - credentials:

          - usernamePassword:
              id: gitea-credentials
              username: git
              password: gitpassword
              description: "Gitea access"
