name: t51

include:
  - ./app/docker-compose-app.yml
  - ./setup/docker-compose-devops.yml

networks:
  t51Net:
    name: t51Net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

volumes:
  t51DB_vol1:
    external: true


