server {
    listen 80;
    server_name 127.0.0.1;
    access_log /var/log/nginx/health_check.log vhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}