jobs:
  - script: >
      pipelineJob('Database-Backup') {
        description('Create a backup of the database.')

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                options {
                    ansiColor('xterm')
                }
                stages {
                   
                  stage('Backup') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1-backup.sh
                      \'\'\'
                    }
                  }

                }
              }
            '''.stripIndent())
          }
        }
      }

