jobs:

  - script: >
      pipelineJob('Database-Rollback-v1') {
        description('Rollback database to previous version.')

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                   
                  stage('1/4 Guard Rail') {
                    steps {
                      input message: 'Did you already created an database backup?', ok: 'Yes, proceed!'
                    }
                  }
                  
                  stage('2/5: Download') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/../Database-Deploy-v1/1md-download-devops-repo.sh
                      \'\'\'
                    }
                  }


                  stage('3/5: Build Image') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/../Database-Deploy-v1/2md-build-image.sh
                      \'\'\'
                    }
                  }

                  stage('4/5: Migrate Rollback') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/../Database-Deploy-v1/3md-migrate.sh rollback
                      \'\'\'
                    }
                  }

                  stage('5/5: Delete last commit') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/4dr-delete-last-commit.sh
                      \'\'\'
                    }
                  }

                }
              }
            '''.stripIndent())
          }
        }
      }