# CAREFUL: Keep sync Pipeline name and working folder in scripts

jobs:
  - script: >
      pipelineJob('Backend-Rollback') {
        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                
                  stage('1/4: Download DevOps and Backend') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/../Backend-Deploy-v1/1bd-download.sh
                      \'\'\'
                    }
                  }

                  stage('2/4: Backup and delete commit in repository') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/2br-backup-and-delete-last-commit.sh
                      \'\'\'
                    }
                  }

                  stage('3/4: Download again but now penultimate commit') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/../Backend-Deploy-v1/1bd-download.sh
                      \'\'\'
                    }
                  }

                  stage('4/4: Build Image') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/../Backend-Deploy-v1/2bd-build-image.sh
                      \'\'\'
                    }
                  }

                  stage('4/4: Deploy') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/../Backend-Deploy-v1/3bd-deploy.sh
                      \'\'\'
                    }
                  }

                }
              }
            '''.stripIndent())
          }
        }
      }

