
jobs:
  - script: >
      pipelineJob('Backend-Tests') {
        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                options {
                    ansiColor('xterm')
                }
                stages {
                  stage('1/X: Download DevOps and Backend') {
                    steps {
                      sh \'\'\'
                        bash $WORKSPACE/../Backend-Deploy-v1/1bd-download.sh
                      \'\'\'
                    }
                  }

                  stage('2/X: unitary tests') {
                    steps {
                      sh \'\'\'
                        bash $WORKSPACE/2bt-run-unitary-tests.sh
                      \'\'\'
                    }
                  }
                } // end stages
                post {
                    always {
                        sh \'\'\'
                            mkdir -p $JENKINS_HOME/userContent
                            rm -f $WORKSPACE/.env
                        \'\'\'
                    }
                    // the file is published in http://jenkins.<DOMAIN>/userContent/backend-tests-result.svg
                    // in my case http://jenkins.mariomv-local.org/userContent/backend-tests-result.svg
                    success {
                        sh \'\'\'
                            cat > $JENKINS_HOME/userContent/backend-tests-result.svg '<svg xmlns="http://www.w3.org/2000/svg" width="110" height="20"><text x="10" y="14">Tests: PASS</text></svg>'
                        \'\'\'
                    }

                    failure {
                        sh \'\'\'
                            cat > $JENKINS_HOME/userContent/backend-tests-result.svg  '<svg xmlns="http://www.w3.org/2000/svg" width="110" height="20"><text x="10" y="14">Tests: FAIL</text></svg>'
                        \'\'\'
                    }
                    
                }
              }
            '''.stripIndent())
          }
        }
      }

