jobs:
  - script: >
      pipelineJob('Frontend-Deploy-v1') {

        triggers {
          genericTrigger {
            token("${FRONT_NAME}-${SHARED_TOKEN}")
            printPostContent(false)
            printContributedVariables(false)
            causeString('Triggered by Gitea Webhook')
          }
        }

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                options {
                    ansiColor('xterm')
                }

                
                stages {

                  stage('1/2: Download') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1fd-download.sh
                      \'\'\'
                    }
                  }

                  stage('2/2: Deploy') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/2fd-deploy.sh
                      \'\'\'
                    }
                  }

                }
              }
            '''.stripIndent())
          }
        }
      }
