
jobs:
  - script: >
      pipelineJob('Backend-Tests') {
        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                options {
                    ansiColor('xterm')
                }
                stages {
                  stage('1/X: Download DevOps and Backend') {
                    steps {
                      sh \'\'\'
                        bash $WORKSPACE/../Backend-Deploy-v1/1bd-download.sh
                      \'\'\'
                    }
                  }

                  stage('2/X: unitary tests') {
                    steps {
                      sh \'\'\'
                        bash $WORKSPACE/2bt-run-unitary-tests.sh
                      \'\'\'
                    }
                  }
                } // end stages
                post {
                    always {
                        sh \'\'\'
                            mkdir -p $JENKINS_HOME/userContent
                            source "/var/jenkins_home/workspace/0_scripts/temp_env_file_functions.sh"
                            remove_copied_env_file "$WORKSPACE/$BUILD_NUMBER/.env"
                        \'\'\'
                    }
                    success {
                        sh \'\'\'
                            cat "/var/jenkins_home/workspace/0_static/badge_success.svg" > \\
                                $JENKINS_HOME/userContent/backend-tests-result.svg
                            echo "published badge to: ^${JENKINS_URL}userContent/backend-tests-result.svg"
                        \'\'\'
                    }
                    failure {
                        sh \'\'\'
                            cat "/var/jenkins_home/workspace/0_static/badge_failing.svg" > \\ 
                                $JENKINS_HOME/userContent/backend-tests-result.svg
                            echo "published badge to: ^${JENKINS_URL}userContent/backend-tests-result.svg"
                        \'\'\'
                    }
                    
              }
                }
            '''.stripIndent())
          }
        }
      }

