jobs:
  - script: >
      pipelineJob('Frontend-Rollback') {

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                  
                  stage('1/4: Download DevOps Project') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1fr-download.sh
                      \'\'\'
                    }
                  }

                  stage('2/4: Backup And Delete Last Commit') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/2fr-backup-and-delete-last-commit.sh
                      \'\'\'
                    }
                  }


                  stage('3/4: Download Penultimate Commit') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/3fr-download-penultimate-commit.sh
                      \'\'\'
                    }
                  }


                  stage('4/4: Rebuild and deploy') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/4fr-rebuild-and-deploy.sh
                      \'\'\'
                    }
                  }

                }
              }
            '''.stripIndent())
          }
        }
      }
