# CAREFUL: Keep sync Pipeline name and working folder in scripts

jobs:
  - script: >
      pipelineJob('Backend-Deploy-v1') {
        
        triggers {
          genericTrigger {
            token("${BACK_NAME}-${SHARED_TOKEN}")

            genericVariables {
              genericVariable {
                // it can help us to determine if is a deploy or a rollback
                key("TOTAL_COMMITS")
                value('$.total_commits')
                expressionType("JSONPath")
              }
            }

            regexpFilterText("\$TOTAL_COMMITS")
            regexpFilterExpression('^[1-9][0-9]*$')  // This regex matches any number that is NOT 0
            // Note '\\' required so can scape and not get an error
            

            //printPostContent(false)
            //printContributedVariables(false)
            causeString('Triggered by Gitea Webhook')
          }
        }

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                  
                  stage('1/2: Download') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1bd-download.sh
                      \'\'\'
                    }
                  }

                  stage('2/2: Deploy') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/2bd-build-and-deploy.sh
                      \'\'\'
                    }
                  }

                }
              }
            '''.stripIndent())
          }
        }
      }
