# CAREFUL: Keep sync Pipeline name and working folder in scripts

jobs:
  - script: >
      pipelineJob('Backend-Rollback') {
        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                
                  stage('1/4: Download DevOps and Backend') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1br-download.sh
                      \'\'\'
                    }
                  }

                  stage('2/4: Backup and delete commit in repository') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/2br-backup-and-delete-last-commit.sh
                      \'\'\'
                    }
                  }

                  stage('3/4: Download penultimate commit') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/3br-download-again.sh
                      \'\'\'
                    }
                  }

                  stage('4/4: Re-build Deploy') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/4br-build-and-deploy.sh
                      \'\'\'
                    }
                  }

                }
              }
            '''.stripIndent())
          }
        }
      }

