jobs:
  - script: |
      pipelineJob('Docker-Commands') {
        description('Manage Docker services')
        
        parameters {
          choiceParam('SERVICE', ['status', 'db', 'back', 'front', 'gitea', 'reverse-proxy' ], 'Select service')
          choiceParam('ACTION', ['none', 'up', 'down', 'restart'], 'Select action')
        }

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }  
                stages {

                  stage('Download') {
                      steps {
                          sh \'\'\'
                              source $WORKSPACE/1dc-download.sh
                          \'\'\'
                      }
                  }

                  stage('Docker Compose Action') {
                      steps {
                          sh "bash $WORKSPACE/2dc-commands.sh ^${params.SERVICE} ^${params.ACTION}" 
                      }
                  }

                  
                }
              }

            '''.stripIndent())
          }
        }
      }
