# CAREFUL: Keep sync Pipeline name and working folder in scripts

jobs:
  - script: >
      pipelineJob('Backend-Rollback') {
        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                
                  stage('1/5: Download DevOps and Backend') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1br-download.sh
                      \'\'\'
                    }
                  }

                  stage('2/5: Backup and delete commit in repository') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/2br-backup-and-delete-last-commit.sh
                      \'\'\'
                    }
                  }

                  stage('3/5: Download penultimate commit') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/3br-download-again.sh
                      \'\'\'
                    }
                  }

                  stage('4/5: Build image') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/4br-build-image.sh
                      \'\'\'
                    }
                  }

                  stage('5/5: Deploy') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/5br-deploy.sh
                      \'\'\'
                    }
                  }


                }
              }
            '''.stripIndent())
          }
        }
      }

