
jobs:
  - script: >

      pipelineJob('t51-build') {

        definition {

          cpsScm {

            scm {

              git {

                remote {
                  url('${BACK_REPO}')
                }

                branch('main')

              }

            }

            scriptPath('Jenkinsfile')

          }

        }

      }
