# CAREFUL: Keep sync Pipeline name and working folder in scripts

jobs:
  - script: >
      pipelineJob('Backend-Deploy-v1') {
        
        triggers {
          genericTrigger {
            token("${BACK_NAME}-${SHARED_TOKEN}")
            printPostContent(false)
            printContributedVariables(false)
            causeString('Triggered by Gitea Webhook')
          }
        }

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                stage('1/3: Download') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1-download.sh
                      \'\'\'
                    }
                  }


                  stage('2/3: Build') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/2-build.sh
                      \'\'\'
                    }
                  }


                  stage('3/3: Deploy') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/3-deploy.sh
                      \'\'\'
                    }
                  }


                }
              }
            '''.stripIndent())
          }
        }
      }


  - script: >
      pipelineJob('Frontend-Deploy-v1') {

        triggers {
          genericTrigger {
            token("${FRONT_NAME}-${SHARED_TOKEN}")
            printPostContent(false)
            printContributedVariables(false)
            causeString('Triggered by Gitea Webhook')
          }
        }

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                stage('1/3: Download') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1f-download.sh
                      \'\'\'
                    }
                  }


                  stage('2/3: Build') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/2f-build.sh
                      \'\'\'
                    }
                  }


                  stage('3/3: Deploy') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/3f-deploy.sh
                      \'\'\'
                    }
                  }


                }
              }
            '''.stripIndent())
          }
        }
      }


  - script: >
      pipelineJob('Database-Deploy-v1') {
        description('Migrate database to next version.')

        triggers {
          genericTrigger {
            token("${DB_MIG_NAME}-${SHARED_TOKEN}")
            printPostContent(false)
            printContributedVariables(false)
            causeString('Triggered by Gitea Webhook')
          }
        }

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                   
                  stage('1/4 Guard Rail') {
                    steps {
                      input message: 'Did you already created an database backup?', ok: 'Yes, proceed!'
                    }
                  }
                  
                  stage('2/4: Download') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1md-download-devops-repo.sh
                      \'\'\'
                    }
                  }


                  stage('3/4: Build Image') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/2md-build-image.sh
                      \'\'\'
                    }
                  }


                  stage('4/4: Migrate Deploy') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/3md-migrate-deploy.sh
                      \'\'\'
                    }
                  }


                }
              }
            '''.stripIndent())
          }
        }
      }

  - script: >
      pipelineJob('Database-Rollback-v1') {
        description('Rollback database to previous version.')

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                   
                  stage('1/4 Guard Rail') {
                    steps {
                      input message: 'Did you already created an database backup?', ok: 'Yes, proceed!'
                    }
                  }
                  
                  stage('2/4: Download') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1md-download-devops-repo.sh
                      \'\'\'
                    }
                  }


                  stage('3/4: Build Image') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/2md-build-image.sh
                      \'\'\'
                    }
                  }

                  stage('4/4: Migrate Rollback') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/3md-migrate.sh rollback
                      \'\'\'
                    }
                  }
                }
              }
            '''.stripIndent())
          }
        }
      }


  - script: |
      pipelineJob('Docker-Control') {
        description('Manage Docker services')
        
        parameters {
          choiceParam('ACTION', ['up -d --wait', 'stop', 'restart'], 'Select action')
          choiceParam('SERVICE', ['db', 'back', 'front', 'gitea', 'reverse-proxy', 'db_backup'], 'Select service')
        }

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                  
                  stage('Guard Rail') {
                    steps {
                      input message: 'Are you sure you want to deploy?', ok: 'Yes, proceed!'
                    }
                  }

                  stage('Download') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1dc-download.sh
                      \'\'\'
                    }
                  }

                  stage('Docker Compose Action') {
                    steps {
                      sh "cd $WORKSPACE/$BUILD_NUMBER && docker compose ^${params.ACTION} ^${params.SERVICE}"
                    }
                  }

                  stage('Verify Status') {
                    steps {
                      sh \'\'\'
                        cd $WORKSPACE/$BUILD_NUMBER
                        docker ps -a --format 'table {{.Names}}\t{{.Status}}\t{{.Size}}'
                      \'\'\'
                    }

                  }
                }
              }
            '''.stripIndent())
          }
        }
      }

  - script: >
      pipelineJob('Database-Backup') {
        description('Create a backup of the database.')

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                   
                  stage('Guard Rail') {
                     steps {
                         input message: 'Are you sure you want to continue?', ok: 'Yes, proceed!'
                     }
                  }

                  stage('Backup') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/1-backup.sh
                      \'\'\'
                    }
                  }

                }
              }
            '''.stripIndent())
          }
        }
      }

  - script: >
      pipelineJob('Database-Restore') {
        description('Restore database using a backup.')

        parameters {
          stringParam('BACKUP_NAME', '', 'Enter the filename of the database backup to restore (e.g. backup_997.sql)')
        }

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                stages {
                   
                  stage('Guard Rail') {
                     steps {
                         input message: 'Are you sure you want to continue?', ok: 'Yes, proceed!'
                     }
                  }

                  stage('Restore') {
                    steps {
                      sh "echo 'Restoring from: ^${params.BACKUP_NAME}'"
                      sh "BACKUP_NAME=^${params.BACKUP_NAME} source $WORKSPACE/1-restore.sh"
                    }
                  }

                }
              }
            '''.stripIndent())
          }
        }
      }
