
jobs:
  - script: >
      pipelineJob('t51Back-2026-v5') {
        definition {
          cps {
            script('''
              pipeline {
                agent any
                stages {
                stage('1/3: Download') {
                    steps {
                      sh \'\'\'
                        source /var/jenkins_home/workspace/back/1-download.sh
                      \'\'\'
                    }
                  }


                  stage('2/3: Build') {
                    steps {
                      sh \'\'\'
                        source /var/jenkins_home/workspace/back/2-build.sh
                      \'\'\'
                    }
                  }


                  stage('3/3: Deploy') {
                    steps {
                      sh \'\'\'
                        source /var/jenkins_home/workspace/back/3-deploy.sh
                      \'\'\'
                    }
                  }


                }
              }
            ''')
          }
        }
      }
  - script: >
      pipelineJob('t51Front-2026-v1') {
        definition {
          cps {
            script('''
              pipeline {
                agent any
                stages {
                stage('1/3: Download') {
                    steps {
                      sh \'\'\'
                        source /var/jenkins_home/workspace/front/1f-download.sh
                      \'\'\'
                    }
                  }


                  stage('2/3: Build') {
                    steps {
                      sh \'\'\'
                        source /var/jenkins_home/workspace/front/2f-build.sh
                      \'\'\'
                    }
                  }


                  stage('3/3: Deploy') {
                    steps {
                      sh \'\'\'
                        source /var/jenkins_home/workspace/front/3f-deploy.sh
                      \'\'\'
                    }
                  }


                }
              }
            ''')
          }
        }
      }