# ■■■■■■■■■■■■■■■■■■■■■■■■■■■- artt -■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■


  artt_db_dev:
    profiles: ["artt"]
    image: ${ART51_DB_IMAGE}
    container_name: artt_db_dev
    volumes:
      - ./data/artt/data/postgresql_dev:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${ART51_DB_NAME}
      POSTGRES_USER: ${ART51_DB_USER}
      POSTGRES_PASSWORD: ${ART51_DB_PASS}
    networks:
      t51Net:
        ipv4_address: ${ART51_DB_HOST}






# docker run -ti --rm --name test -w /dist -v ./data/artt:/dist --network template51_t51Net alpine:3.22.1 sh


  artt_server_dev:
    profiles: ["artt"]
    image: alpine:3.22
    container_name: artt_server_dev
    environment:
      - VIRTUAL_HOST=artesaniastlaxco.duckdns.org
      - VIRTUAL_PORT=${ART51_PORT}
      - LETSENCRYPT_HOST=artesaniastlaxco.duckdns.org
      - LETSENCRYPT_EMAIL=${ART51_MY_EMAIL}
    depends_on:
      - artt_db_dev
    working_dir: /dist
    volumes:
      - ./data/artt:/dist
    command: ["./artt_server.exe"]
    expose:
      - ${ART51_PORT}
    networks:
      t51Net:
        ipv4_address: 172.30.0.71

