
services:

  db:
    profiles: ["app", "all"]
    container_name: ${DB_SERVER}
    image: ${DB_IMAGE}
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      t51Net:
        ipv4_address: ${DB_IP}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_SCHEMA}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "PGDATABASE=${DB_SCHEMA} pg_isready -U ${DB_USER} -h localhost"]
      interval: 20s
      timeout: 5s
      retries: 5


  back:
    profiles: ["app", "all"]
    container_name: ${BACK_NAME}
    image: ${BACK_IMAGE}
    build:
      context: ./back
      dockerfile: back.dockerfile
      args:
        TEST: 1   # Ignore just for testing
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=api.${MY_DOMAIN}
      - LETSENCRYPT_HOST=api.${MY_DOMAIN}
      - LETSENCRYPT_EMAIL=${MY_EMAIL}
      - VIRTUAL_PORT=8080
      # DB connection data
      - DB_SERVER=${DB_SERVER}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
      t51Net:
        ipv4_address: ${BACK_IP}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health && echo servicesAlive"]
      interval: 20s
      retries: 5



  front:
    profiles: ["app", "all"]
    container_name: ${FRONT_NAME}
    build:
      context: ./front
      args:
        BACK_URL: ${BACK_URL}
      dockerfile: front.dockerfile
    image: ${FRONT_IMAGE}
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${MY_DOMAIN}
      - LETSENCRYPT_HOST=${MY_DOMAIN}
      - LETSENCRYPT_EMAIL=${MY_EMAIL}
      - VIRTUAL_PORT=80
    networks:
      t51Net:
        ipv4_address: ${FRONT_IP}
    depends_on:
      back:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1 && echo servicesAlive"]
      interval: 20s
      retries: 5


## Maintenance

# run with: "docker compose run --rm db_migrate deploy" for deploy
# or use    "docker compose run --rm db_migrate rollback" for rollback
  db_migrate:
    profiles: ["devops-util"]
    container_name: ${DB_MIG_NAME}
    image: t51migrator:1
    build:
      context: ./db
      args:
        DB_MIG_IMAGE: ${DB_MIG_IMAGE}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_SERVER: ${DB_SERVER}
        DB_SCHEMA: ${DB_SCHEMA}
      dockerfile: migrator.dockerfile
    entrypoint: [ "bash", "/app/migrator.entrypoint.sh" ]

    
    
    #volumes:                           # AVOIDING THIS, BECAUSE i HAD PROBLEMS WITH HOST VOLUMES AND DinD
     # - ./db/source:/var/my_migrations
    #depends_on:
    #  db:                              # AVOID THIS, IT MIGHT RECREATE THE DATABASE VOLUME ¡¡DELETING!! ALL, BETTER CHECK THE LOGS
    #    condition: service_healthy
    
    networks:
      - t51Net
    restart: "no"


  # run it manually with: "BUILD_NUMBER=1 docker compose run --rm --no-deps db_backup"
  db_backup:
    profiles: ["devops-util"]
    container_name: db_backup
    build:
      context: ./utils
      dockerfile: alpine-utils.dockerfile
    image: utils:1
    environment:
      - PGPASSWORD=${DB_PASS}
      - BUILD_NUMBER=${BUILD_NUMBER}
    volumes:
      - ./data/db_backups:/app/backups/
    entrypoint: [ "bash", "-c", "pg_dump -h ${DB_IP} -U ${DB_USER} -d ${DB_SCHEMA} -F p > /app/backups/db_backup_$(echo $BUILD_NUMBER)_$(date +'%Y-%m-%d_%H-%M-%S').sql" ]
    networks:
      - t51Net
    depends_on:
      db:
        condition: service_healthy
    restart: "no"



  # run it manually with: "BACKUP_NAME=1 docker compose run --rm --no-deps db_backup"
  db_restore:
    profiles: ["devops-util"]
    container_name: db_restore
    build:
      context: ./utils
      dockerfile: alpine-utils.dockerfile
    image: utils:1
    environment:
      - PGPASSWORD=${DB_PASS}
      - BACKUP_NAME=${BACKUP_NAME}
    volumes:
      - ./data/db_backups:/app/backups/:ro
    working_dir: /app/backups
    entrypoint: [ "bash", "-c", "psql -U ${DB_USER} -d ${DB_SCHEMA} < ./${BACKUP_NAME}" ]
    networks:
      - t51Net
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
