
services:

  gitea:
    profiles: ["devops", "all"]
    container_name: gitea       # Careful changing it's used to clone the repo in jenkins
    image: gitea/gitea:1.25
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - VIRTUAL_HOST=gitea.${MY_DOMAIN}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=gitea.${MY_DOMAIN}
      - LETSENCRYPT_EMAIL=${MY_EMAIL}
      # Gitea Config
      - GITEA__security__INSTALL_LOCK=true
      - GITEA_ADMIN_USER=${MY_USER}
      - GITEA_ADMIN_PASSWORD=${MY_PASS}
      - GITEA_ADMIN_EMAIL=${MY_EMAIL}
      - GITEA__server__DOMAIN=gitea.${MY_DOMAIN}
      - GITEA__server__SSH_DOMAIN=gitea.${MY_DOMAIN}
      - GITEA__server__ROOT_URL=http://gitea.${MY_DOMAIN}/
      - GITEA__webhook__ALLOWED_HOST_LIST=jenkins,172.30.0.0/16,external
      # Initial repositories
      - BACK_NAME=${BACK_NAME}
      - FRONT_NAME=${FRONT_NAME}
      - DB_MIG_NAME=${DB_MIG_NAME}
      - DEVOPS_NAME=${DEVOPS_NAME}
      - SHARED_TOKEN=${SHARED_TOKEN}
    volumes:
      - ./gitea/vol-data:/data    # Persist data
      - ./gitea/gitea-entrypoint.sh:/usr/local/bin/gitea-entrypoint.sh:ro   # Config
      - ./secrets/t51_noPass.pub:/data/setup/t51_noPass.pub:ro    # SSH Config
      # Initial repositories
      - ./gitea/initial_repos/${BACK_NAME}.tar.xz:/tmp/initial_repos/${BACK_NAME}.tar.xz
      - ./gitea/initial_repos/${FRONT_NAME}.tar.xz:/tmp/initial_repos/${FRONT_NAME}.tar.xz
      - ./gitea/initial_repos/${DB_MIG_NAME}.tar.xz:/tmp/initial_repos/${DB_MIG_NAME}.tar.xz
      - ./gitea/initial_repos/${DEVOPS_NAME}.tar.xz:/tmp/initial_repos/${DEVOPS_NAME}.tar.xz
      # Time sync
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["/bin/sh", "/usr/local/bin/gitea-entrypoint.sh"]
    ports:
      - "222:22"
    expose:
      - "3000"
    networks:
      t51Net:
        ipv4_address: ${GITEA_IP}




  #C1: CAREFUL: Might give file permissions error, if does run: "sudo chown -R 1000:1000 ./data_jenkins"
  #C2:--CAREFUL changing the name, is used trigger the webhook from gitea to jenkins.
  #C2:----./.env
  #C2:----./data/secrets/ssh/config 
  #C2:----./workdir/start.sh
  #C2:----./workdir/database_rollback.sh
  jenkins:
    profiles: ["devops", "all"]
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: jenkins-with-docker.dockerfile
    privileged: true
    environment:
      - JENKINS_JAVA_OPTS="-Dhudson.model.ParametersAction.keepUndefinedParameters=false"
      - VIRTUAL_HOST=jenkins.${MY_DOMAIN}
      - LETSENCRYPT_HOST=jenkins.${MY_DOMAIN}
      - LETSENCRYPT_EMAIL=${MY_EMAIL}
      - VIRTUAL_PORT=8080
      # JCasC (Jenkins Code as Configuration)
      - MY_USER=${MY_USER}
      - MY_PASS=${MY_PASS}
      - MY_DOMAIN=${MY_DOMAIN}
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
      # Pipeline variables
      - DB_MIG_REPO=${DB_MIG_REPO}
      - DB_MIG_NAME=${DB_MIG_NAME}
      - BACK_REPO=${BACK_REPO}
      - BACK_NAME=${BACK_NAME}
      - FRONT_REPO=${FRONT_REPO}
      - FRONT_NAME=${FRONT_NAME}
      - DEVOPS_REPO=${DEVOPS_REPO}
      - DEVOPS_WORKDIR=${DEVOPS_WORKDIR}
      - VERSION=${VERSION}
      - SHARED_TOKEN=${SHARED_TOKEN}
    expose:
      - "8080"
    volumes:

####### REPO LOCATIONS ########
      - ./jenkins/vol-jenkins_home:/var/jenkins_home        # all jenkins main
      - ./jenkins/casc:/var/jenkins_home/casc_configs:ro    # CasC (Configuration as Code)
      - ../workspace:${DEVOPS_WORKDIR}                      # executions and generations of DevOps Process
      - ../.env:${DEVOPS_WORKDIR}/.env:ro         # for testing scripts in container shell terminal
# SSH conf to add gitea as reliable server
      - ./secrets/t51_noPass.priv:/var/jenkins_home/.ssh/t51_noPass.priv:ro
      - ./shared/ssh_config:/var/jenkins_home/.ssh/config
      - ./shared/known_hosts:/var/jenkins_home/.ssh/known_hosts


####### SYSTEM LOCATIONS ########
# Access to docker host
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker
#Sync time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      t51Net:
        ipv4_address: ${JENKINS_IP}


  reverse-proxy:
    profiles: ["gateway", "all"]
    image: nginxproxy/nginx-proxy:1.10-alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/reverse-proxy/certs:/etc/nginx/certs:rw
      - ./data/reverse-proxy/vhost.d:/etc/nginx/vhost.d
      - ./data/reverse-proxy/html:/usr/share/nginx/html
    networks:
      t51Net:
        ipv4_address: ${REVERSE_PROXY_IP}


# for automatic SSL certificate management
# IMPORTANT: run it at the end: 
  acme-companion:
    profiles: ["gateway"]
    image: nginxproxy/acme-companion:2.6
    container_name: acme-companion
    depends_on:
      - reverse-proxy
    environment:
      - DEFAULT_EMAIL=${MY_EMAIL}
      - NGINX_PROXY_CONTAINER=reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/reverse-proxy/certs:/etc/nginx/certs:rw
      - ./data/reverse-proxy/vhost.d:/etc/nginx/vhost.d
      - ./data/reverse-proxy/html:/usr/share/nginx/html
      - ./data/reverse-proxy/acme:/etc/acme.sh
    networks:
      t51Net:
        ipv4_address: ${ACME_COMPANION_IP}


